# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeatherData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WeatherData.proto',
  package='WeatherData',
  syntax='proto3',
  serialized_options=_b('\252\002\017unwdmi.Protobuf'),
  serialized_pb=_b('\n\x11WeatherData.proto\x12\x0bWeatherData\"k\n\x0bMeasurement\x12\x11\n\tStationID\x18\x01 \x01(\r\x12\x10\n\x08\x44\x61teTime\x18\x02 \x01(\x03\x12\x10\n\x08Humidity\x18\x03 \x01(\x01\x12\x11\n\tWindSpeed\x18\x04 \x01(\x02\x12\x12\n\nCloudCover\x18\x05 \x01(\x02\"~\n\x0eWeatherStation\x12\x15\n\rStationNumber\x18\x01 \x01(\r\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07\x43ountry\x18\x03 \x01(\t\x12\x10\n\x08Latitude\x18\x04 \x01(\x01\x12\x11\n\tLongitude\x18\x05 \x01(\x01\x12\x11\n\tElevation\x18\x06 \x01(\x01\"d\n\x07Request\x12-\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1c.WeatherData.Request.Command\"*\n\x07\x43ommand\x12\x0f\n\x0bWeatherData\x10\x00\x12\x0e\n\nCloudCover\x10\x01\"\r\n\x0bWeatherData\"\x0c\n\nCloudCoverB\x12\xaa\x02\x0funwdmi.Protobufb\x06proto3')
)



_REQUEST_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='WeatherData.Request.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WeatherData', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CloudCover', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=329,
  serialized_end=371,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_COMMAND)


_MEASUREMENT = _descriptor.Descriptor(
  name='Measurement',
  full_name='WeatherData.Measurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='StationID', full_name='WeatherData.Measurement.StationID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DateTime', full_name='WeatherData.Measurement.DateTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity', full_name='WeatherData.Measurement.Humidity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WindSpeed', full_name='WeatherData.Measurement.WindSpeed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CloudCover', full_name='WeatherData.Measurement.CloudCover', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=141,
)


_WEATHERSTATION = _descriptor.Descriptor(
  name='WeatherStation',
  full_name='WeatherData.WeatherStation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='StationNumber', full_name='WeatherData.WeatherStation.StationNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='WeatherData.WeatherStation.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Country', full_name='WeatherData.WeatherStation.Country', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='WeatherData.WeatherStation.Latitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='WeatherData.WeatherStation.Longitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Elevation', full_name='WeatherData.WeatherStation.Elevation', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=269,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='WeatherData.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='WeatherData.Request.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_COMMAND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=371,
)


_WEATHERDATA = _descriptor.Descriptor(
  name='WeatherData',
  full_name='WeatherData.WeatherData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=353,
)


_CLOUDCOVER = _descriptor.Descriptor(
  name='CloudCover',
  full_name='WeatherData.CloudCover',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=135,
)

_REQUEST.fields_by_name['command'].enum_type = _REQUEST_COMMAND
_REQUEST_COMMAND.containing_type = _REQUEST
DESCRIPTOR.message_types_by_name['Measurement'] = _MEASUREMENT
DESCRIPTOR.message_types_by_name['WeatherStation'] = _WEATHERSTATION
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['WeatherData'] = _WEATHERDATA
DESCRIPTOR.message_types_by_name['CloudCover'] = _CLOUDCOVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Measurement = _reflection.GeneratedProtocolMessageType('Measurement', (_message.Message,), dict(
  DESCRIPTOR = _MEASUREMENT,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.Measurement)
  ))
_sym_db.RegisterMessage(Measurement)

WeatherStation = _reflection.GeneratedProtocolMessageType('WeatherStation', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERSTATION,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.WeatherStation)
  ))
_sym_db.RegisterMessage(WeatherStation)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.Request)
  ))
_sym_db.RegisterMessage(Request)

WeatherData = _reflection.GeneratedProtocolMessageType('WeatherData', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERDATA,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.WeatherData)
  ))
_sym_db.RegisterMessage(WeatherData)

CloudCover = _reflection.GeneratedProtocolMessageType('CloudCover', (_message.Message,), dict(
  DESCRIPTOR = _CLOUDCOVER,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.CloudCover)
  ))
_sym_db.RegisterMessage(CloudCover)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
