# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: website.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='website.proto',
  package='opdracht',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rwebsite.proto\x12\x08opdracht\"\x1c\n\x0ctop10request\x12\x0c\n\x04land\x18\x01 \x01(\t\"\xba\x01\n\rtop10response\x12\x0f\n\x07nummer1\x18\x01 \x01(\t\x12\x0f\n\x07nummer2\x18\x02 \x01(\t\x12\x0f\n\x07nummer3\x18\x03 \x01(\t\x12\x0f\n\x07nummer4\x18\x04 \x01(\t\x12\x0f\n\x07nummer5\x18\x05 \x01(\t\x12\x0f\n\x07nummer6\x18\x06 \x01(\t\x12\x0f\n\x07nummer7\x18\x07 \x01(\t\x12\x0f\n\x07nummer8\x18\x08 \x01(\t\x12\x0f\n\x07nummer9\x18\t \x01(\t\x12\x10\n\x08nummer10\x18\n \x01(\t\"#\n\x10windspeedrequest\x12\x0f\n\x07station\x18\x01 \x01(\t\"7\n\x11windspeedresponse\x12\x0c\n\x04tijd\x18\x01 \x01(\t\x12\x14\n\x0cwindsnelheid\x18\x02 \x01(\x02\"#\n\x10humidity_request\x12\x0f\n\x07station\x18\x01 \x01(\t\"3\n\x11humidity_response\x12\x0c\n\x04tijd\x18\x01 \x01(\t\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x32\xd9\x01\n\x06UNWDMI\x12H\n\tWindspeed\x12\x1a.opdracht.windspeedrequest\x1a\x1b.opdracht.windspeedresponse\"\x00\x30\x01\x12<\n\x07toptien\x12\x16.opdracht.top10request\x1a\x17.opdracht.top10response\"\x00\x12G\n\x08Humidity\x12\x1a.opdracht.humidity_request\x1a\x1b.opdracht.humidity_response\"\x00\x30\x01\x62\x06proto3')
)




_TOP10REQUEST = _descriptor.Descriptor(
  name='top10request',
  full_name='opdracht.top10request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='land', full_name='opdracht.top10request.land', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=55,
)


_TOP10RESPONSE = _descriptor.Descriptor(
  name='top10response',
  full_name='opdracht.top10response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nummer1', full_name='opdracht.top10response.nummer1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer2', full_name='opdracht.top10response.nummer2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer3', full_name='opdracht.top10response.nummer3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer4', full_name='opdracht.top10response.nummer4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer5', full_name='opdracht.top10response.nummer5', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer6', full_name='opdracht.top10response.nummer6', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer7', full_name='opdracht.top10response.nummer7', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer8', full_name='opdracht.top10response.nummer8', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer9', full_name='opdracht.top10response.nummer9', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nummer10', full_name='opdracht.top10response.nummer10', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=244,
)


_WINDSPEEDREQUEST = _descriptor.Descriptor(
  name='windspeedrequest',
  full_name='opdracht.windspeedrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='station', full_name='opdracht.windspeedrequest.station', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=281,
)


_WINDSPEEDRESPONSE = _descriptor.Descriptor(
  name='windspeedresponse',
  full_name='opdracht.windspeedresponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tijd', full_name='opdracht.windspeedresponse.tijd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='windsnelheid', full_name='opdracht.windspeedresponse.windsnelheid', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=338,
)


_HUMIDITY_REQUEST = _descriptor.Descriptor(
  name='humidity_request',
  full_name='opdracht.humidity_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='station', full_name='opdracht.humidity_request.station', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=375,
)


_HUMIDITY_RESPONSE = _descriptor.Descriptor(
  name='humidity_response',
  full_name='opdracht.humidity_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tijd', full_name='opdracht.humidity_response.tijd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='opdracht.humidity_response.humidity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=428,
)

DESCRIPTOR.message_types_by_name['top10request'] = _TOP10REQUEST
DESCRIPTOR.message_types_by_name['top10response'] = _TOP10RESPONSE
DESCRIPTOR.message_types_by_name['windspeedrequest'] = _WINDSPEEDREQUEST
DESCRIPTOR.message_types_by_name['windspeedresponse'] = _WINDSPEEDRESPONSE
DESCRIPTOR.message_types_by_name['humidity_request'] = _HUMIDITY_REQUEST
DESCRIPTOR.message_types_by_name['humidity_response'] = _HUMIDITY_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

top10request = _reflection.GeneratedProtocolMessageType('top10request', (_message.Message,), dict(
  DESCRIPTOR = _TOP10REQUEST,
  __module__ = 'website_pb2'
  # @@protoc_insertion_point(class_scope:opdracht.top10request)
  ))
_sym_db.RegisterMessage(top10request)

top10response = _reflection.GeneratedProtocolMessageType('top10response', (_message.Message,), dict(
  DESCRIPTOR = _TOP10RESPONSE,
  __module__ = 'website_pb2'
  # @@protoc_insertion_point(class_scope:opdracht.top10response)
  ))
_sym_db.RegisterMessage(top10response)

windspeedrequest = _reflection.GeneratedProtocolMessageType('windspeedrequest', (_message.Message,), dict(
  DESCRIPTOR = _WINDSPEEDREQUEST,
  __module__ = 'website_pb2'
  # @@protoc_insertion_point(class_scope:opdracht.windspeedrequest)
  ))
_sym_db.RegisterMessage(windspeedrequest)

windspeedresponse = _reflection.GeneratedProtocolMessageType('windspeedresponse', (_message.Message,), dict(
  DESCRIPTOR = _WINDSPEEDRESPONSE,
  __module__ = 'website_pb2'
  # @@protoc_insertion_point(class_scope:opdracht.windspeedresponse)
  ))
_sym_db.RegisterMessage(windspeedresponse)

humidity_request = _reflection.GeneratedProtocolMessageType('humidity_request', (_message.Message,), dict(
  DESCRIPTOR = _HUMIDITY_REQUEST,
  __module__ = 'website_pb2'
  # @@protoc_insertion_point(class_scope:opdracht.humidity_request)
  ))
_sym_db.RegisterMessage(humidity_request)

humidity_response = _reflection.GeneratedProtocolMessageType('humidity_response', (_message.Message,), dict(
  DESCRIPTOR = _HUMIDITY_RESPONSE,
  __module__ = 'website_pb2'
  # @@protoc_insertion_point(class_scope:opdracht.humidity_response)
  ))
_sym_db.RegisterMessage(humidity_response)



_UNWDMI = _descriptor.ServiceDescriptor(
  name='UNWDMI',
  full_name='opdracht.UNWDMI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=431,
  serialized_end=648,
  methods=[
  _descriptor.MethodDescriptor(
    name='Windspeed',
    full_name='opdracht.UNWDMI.Windspeed',
    index=0,
    containing_service=None,
    input_type=_WINDSPEEDREQUEST,
    output_type=_WINDSPEEDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='toptien',
    full_name='opdracht.UNWDMI.toptien',
    index=1,
    containing_service=None,
    input_type=_TOP10REQUEST,
    output_type=_TOP10RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Humidity',
    full_name='opdracht.UNWDMI.Humidity',
    index=2,
    containing_service=None,
    input_type=_HUMIDITY_REQUEST,
    output_type=_HUMIDITY_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UNWDMI)

DESCRIPTOR.services_by_name['UNWDMI'] = _UNWDMI

# @@protoc_insertion_point(module_scope)
