# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import website_pb2 as website__pb2


class UNWDMIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Windspeed = channel.unary_unary(
        '/opdracht.UNWDMI/Windspeed',
        request_serializer=website__pb2.windspeedrequest.SerializeToString,
        response_deserializer=website__pb2.windspeedresponse.FromString,
        )
    self.toptien = channel.unary_unary(
        '/opdracht.UNWDMI/toptien',
        request_serializer=website__pb2.top10request.SerializeToString,
        response_deserializer=website__pb2.top10response.FromString,
        )


class UNWDMIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Windspeed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def toptien(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UNWDMIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Windspeed': grpc.unary_unary_rpc_method_handler(
          servicer.Windspeed,
          request_deserializer=website__pb2.windspeedrequest.FromString,
          response_serializer=website__pb2.windspeedresponse.SerializeToString,
      ),
      'toptien': grpc.unary_unary_rpc_method_handler(
          servicer.toptien,
          request_deserializer=website__pb2.top10request.FromString,
          response_serializer=website__pb2.top10response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'opdracht.UNWDMI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
