# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeatherData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WeatherData.proto',
  package='WeatherData',
  syntax='proto3',
  serialized_options=_b('\252\002\017unwdmi.Protobuf'),
  serialized_pb=_b('\n\x11WeatherData.proto\x12\x0bWeatherData\"k\n\x0bMeasurement\x12\x11\n\tStationID\x18\x01 \x01(\r\x12\x10\n\x08\x44\x61teTime\x18\x02 \x01(\x03\x12\x10\n\x08Humidity\x18\x03 \x01(\x01\x12\x11\n\tWindSpeed\x18\x04 \x01(\x02\x12\x12\n\nCloudCover\x18\x05 \x01(\x02\"~\n\x0eWeatherStation\x12\x15\n\rStationNumber\x18\x01 \x01(\r\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07\x43ountry\x18\x03 \x01(\t\x12\x10\n\x08Latitude\x18\x04 \x01(\x01\x12\x11\n\tLongitude\x18\x05 \x01(\x01\x12\x11\n\tElevation\x18\x06 \x01(\x01\"*\n\x07\x43ountry\x12\x0f\n\x07\x43ountry\x18\x01 \x01(\t\x12\x0e\n\x06Ignore\x18\x02 \x01(\x08\"\xc2\x03\n\x06TopTen\x12\x17\n\x0fWeatherStation1\x18\x01 \x01(\r\x12\x11\n\tHumidity1\x18\x02 \x01(\x02\x12\x17\n\x0fWeatherStation2\x18\x03 \x01(\r\x12\x11\n\tHumidity2\x18\x04 \x01(\x02\x12\x17\n\x0fWeatherStation3\x18\x05 \x01(\r\x12\x11\n\tHumidity3\x18\x06 \x01(\x02\x12\x17\n\x0fWeatherStation4\x18\x07 \x01(\r\x12\x11\n\tHumidity4\x18\x08 \x01(\x02\x12\x17\n\x0fWeatherStation5\x18\t \x01(\r\x12\x11\n\tHumidity5\x18\n \x01(\x02\x12\x17\n\x0fWeatherStation6\x18\x0b \x01(\r\x12\x11\n\tHumidity6\x18\x0c \x01(\x02\x12\x17\n\x0fWeatherStation7\x18\r \x01(\r\x12\x11\n\tHumidity7\x18\x0e \x01(\x02\x12\x17\n\x0fWeatherStation8\x18\x0f \x01(\r\x12\x11\n\tHumidity8\x18\x10 \x01(\x02\x12\x17\n\x0fWeatherStation9\x18\x11 \x01(\r\x12\x11\n\tHumidity9\x18\x12 \x01(\x02\x12\x18\n\x10WeatherStation10\x18\x13 \x01(\r\x12\x12\n\nHumidity10\x18\x14 \x01(\x02\x42\x12\xaa\x02\x0funwdmi.Protobufb\x06proto3')
)




_MEASUREMENT = _descriptor.Descriptor(
  name='Measurement',
  full_name='WeatherData.Measurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='StationID', full_name='WeatherData.Measurement.StationID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DateTime', full_name='WeatherData.Measurement.DateTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity', full_name='WeatherData.Measurement.Humidity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WindSpeed', full_name='WeatherData.Measurement.WindSpeed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CloudCover', full_name='WeatherData.Measurement.CloudCover', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=141,
)


_WEATHERSTATION = _descriptor.Descriptor(
  name='WeatherStation',
  full_name='WeatherData.WeatherStation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='StationNumber', full_name='WeatherData.WeatherStation.StationNumber', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='WeatherData.WeatherStation.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Country', full_name='WeatherData.WeatherStation.Country', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Latitude', full_name='WeatherData.WeatherStation.Latitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Longitude', full_name='WeatherData.WeatherStation.Longitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Elevation', full_name='WeatherData.WeatherStation.Elevation', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=269,
)


_COUNTRY = _descriptor.Descriptor(
  name='Country',
  full_name='WeatherData.Country',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Country', full_name='WeatherData.Country.Country', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ignore', full_name='WeatherData.Country.Ignore', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=313,
)


_TOPTEN = _descriptor.Descriptor(
  name='TopTen',
  full_name='WeatherData.TopTen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WeatherStation1', full_name='WeatherData.TopTen.WeatherStation1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity1', full_name='WeatherData.TopTen.Humidity1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation2', full_name='WeatherData.TopTen.WeatherStation2', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity2', full_name='WeatherData.TopTen.Humidity2', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation3', full_name='WeatherData.TopTen.WeatherStation3', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity3', full_name='WeatherData.TopTen.Humidity3', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation4', full_name='WeatherData.TopTen.WeatherStation4', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity4', full_name='WeatherData.TopTen.Humidity4', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation5', full_name='WeatherData.TopTen.WeatherStation5', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity5', full_name='WeatherData.TopTen.Humidity5', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation6', full_name='WeatherData.TopTen.WeatherStation6', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity6', full_name='WeatherData.TopTen.Humidity6', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation7', full_name='WeatherData.TopTen.WeatherStation7', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity7', full_name='WeatherData.TopTen.Humidity7', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation8', full_name='WeatherData.TopTen.WeatherStation8', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity8', full_name='WeatherData.TopTen.Humidity8', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation9', full_name='WeatherData.TopTen.WeatherStation9', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity9', full_name='WeatherData.TopTen.Humidity9', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeatherStation10', full_name='WeatherData.TopTen.WeatherStation10', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Humidity10', full_name='WeatherData.TopTen.Humidity10', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=766,
)

DESCRIPTOR.message_types_by_name['Measurement'] = _MEASUREMENT
DESCRIPTOR.message_types_by_name['WeatherStation'] = _WEATHERSTATION
DESCRIPTOR.message_types_by_name['Country'] = _COUNTRY
DESCRIPTOR.message_types_by_name['TopTen'] = _TOPTEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Measurement = _reflection.GeneratedProtocolMessageType('Measurement', (_message.Message,), dict(
  DESCRIPTOR = _MEASUREMENT,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.Measurement)
  ))
_sym_db.RegisterMessage(Measurement)

WeatherStation = _reflection.GeneratedProtocolMessageType('WeatherStation', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERSTATION,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.WeatherStation)
  ))
_sym_db.RegisterMessage(WeatherStation)

Country = _reflection.GeneratedProtocolMessageType('Country', (_message.Message,), dict(
  DESCRIPTOR = _COUNTRY,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.Country)
  ))
_sym_db.RegisterMessage(Country)

TopTen = _reflection.GeneratedProtocolMessageType('TopTen', (_message.Message,), dict(
  DESCRIPTOR = _TOPTEN,
  __module__ = 'WeatherData_pb2'
  # @@protoc_insertion_point(class_scope:WeatherData.TopTen)
  ))
_sym_db.RegisterMessage(TopTen)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
